/* Generated By:JavaCC: Do not edit this line. eg1Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface eg1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DO = 11;
  /** RegularExpression Id. */
  int WHILE = 12;
  /** RegularExpression Id. */
  int TRUE = 13;
  /** RegularExpression Id. */
  int FALSE = 14;
  /** RegularExpression Id. */
  int IF = 15;
  /** RegularExpression Id. */
  int VAR = 16;
  /** RegularExpression Id. */
  int RETURN = 17;
  /** RegularExpression Id. */
  int NEW = 18;
  /** RegularExpression Id. */
  int ARRAY = 19;
  /** RegularExpression Id. */
  int PROMPT = 20;
  /** RegularExpression Id. */
  int DOCUMENT = 21;
  /** RegularExpression Id. */
  int WRITE = 22;
  /** RegularExpression Id. */
  int FUNCTION = 23;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 24;
  /** RegularExpression Id. */
  int LETRA = 25;
  /** RegularExpression Id. */
  int DIGITO = 26;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 27;
  /** RegularExpression Id. */
  int STRING_LITERAL = 28;
  /** RegularExpression Id. */
  int PARENDRCHA = 29;
  /** RegularExpression Id. */
  int PARENIZQ = 30;
  /** RegularExpression Id. */
  int LLAVEDRCHA = 31;
  /** RegularExpression Id. */
  int LLAVEIZQ = 32;
  /** RegularExpression Id. */
  int CORCHETEDRCHA = 33;
  /** RegularExpression Id. */
  int CORCHETEIZQ = 34;
  /** RegularExpression Id. */
  int PUNTOYCOMA = 35;
  /** RegularExpression Id. */
  int COMA = 36;
  /** RegularExpression Id. */
  int PUNTO = 37;
  /** RegularExpression Id. */
  int ASIGNACION = 38;
  /** RegularExpression Id. */
  int MAYOR = 39;
  /** RegularExpression Id. */
  int MENOR = 40;
  /** RegularExpression Id. */
  int MAS = 41;
  /** RegularExpression Id. */
  int MENOS = 42;
  /** RegularExpression Id. */
  int MUL = 43;
  /** RegularExpression Id. */
  int DIV = 44;
  /** RegularExpression Id. */
  int MODULO = 45;
  /** RegularExpression Id. */
  int INTERROGANTE = 46;
  /** RegularExpression Id. */
  int DOSPUNTOS = 47;
  /** RegularExpression Id. */
  int IGUAL = 48;
  /** RegularExpression Id. */
  int MENORIGUAL = 49;
  /** RegularExpression Id. */
  int MAYORIGUAL = 50;
  /** RegularExpression Id. */
  int DISTINTO = 51;
  /** RegularExpression Id. */
  int OR = 52;
  /** RegularExpression Id. */
  int AND = 53;
  /** RegularExpression Id. */
  int INC = 54;
  /** RegularExpression Id. */
  int DEC = 55;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int COMENTARIOS = 1;
  /** Lexical state. */
  int COMENTARIOS_UNA_LINEA = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"/*\"",
    "\"//\"",
    "\"*/\"",
    "<token of kind 8>",
    "\"\\n\"",
    "<token of kind 10>",
    "\"do\"",
    "\"while\"",
    "\"true\"",
    "\"false\"",
    "\"if\"",
    "\"var\"",
    "\"return\"",
    "\"new\"",
    "\"Array\"",
    "\"prompt\"",
    "\"document\"",
    "\"write\"",
    "\"function\"",
    "<IDENTIFICADOR>",
    "<LETRA>",
    "<DIGITO>",
    "<INTEGER_LITERAL>",
    "<STRING_LITERAL>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
  };

}
